apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 4
  selector:
    app: mylogin-rc
  template:
    metadata:
      name: mylogin
      labels:
        app: mylogin
    spec:
      containers:
        - name: mylogin-container
          image: 7658941768/mymay:1
          ports:
            - containerPort: 8080

