
apiVersion: v1
kind: ReplicationController
metadata:
  name:  mylogin-rc
spec:
  replicas: 3
  selector:
     app:  mylogin
     version: 2.6.1
  template:
    metadata:
       labels:
          app: mylogin
          version: 2.6.1
    spec:
      containers:
      - name: mylogin-container   
        image: 7658941768/mymay22:1
        ports:
         - containerPort: 8080 